name: autofix.ci

on:
  push:
    branches: [main]

  pull_request:

  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: pnpm lint --fix

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Setup JS (push event)
        if: github.event_name == 'push'
        uses: yikoyu/workflows/setup-js@main

      - name: Setup JS (pull_request_target event)
        if: github.event_name == 'pull_request_target'
        uses: yikoyu/workflows/setup-js@main
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false

      - name: Fix
        run: ${{ inputs.command }}
        if: ${{ inputs.command != '' }}

      - name: Commit
        uses: autofix-ci/action@v1
        with:
          commit-message: 'ci(autofix): :lipstick: auto format [skip ci]'
