name: Commitlint Validate

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: [ubuntu-latest]

    steps:
      - name: Setup JS (push event)
        if: github.event_name == 'push'
        uses: yikoyu/workflows/setup-js@main
        with:
          fetch-all: 'true'

      - name: Setup JS (pull_request_target event)
        if: github.event_name == 'pull_request_target'
        uses: yikoyu/workflows/setup-js@main
        with:
          fetch-all: true
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request_target'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
